name: 'PR'
on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: yarn install --immutable
      - name: Typescript build
        run: yarn build:tsc
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
