name: 'PR'
on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Flow
        run: |
          yarn install --immutable
          yarn build:tsc
        shell: bash
